### ISSUE TITLE
Not scraping anymore?

### ISSUE THREAD

**Issue by aronprins** [autoclick/fb-uid-scraper#6]
I click on Get UID and it's not scraping anymore?
Thanks in advance!

**Comment by autoclick** [comment]
I cant help you with only that info
please install newest version and give me graph search link

**Comment by aronprins** [comment]
This is what I get when I search:
https://www.facebook.com/search/str/people%20interested%20in%20dating/keywords_top

Let me know if you need any other details :)

**Comment by autoclick** [comment]
Please watch video and do like that https://www.youtube.com/watch?v=5LcCO6qURQ4
this is correct link: https://www.facebook.com/search/107832345906445/likers?ref=content_filter

**Comment by aronprins** [comment]
How can I make it so it automatically gives me a url like that?

**Comment by autoclick** [comment]
find id of page "Dating" and replace in link

**Comment by aronprins** [comment]
Ok - it worked great before though! How can we get in touch via e-mail :)?

**Comment by aronprins** [comment]
Please note: It's currently still not working :(

**Comment by autoclick** [comment]
please install newest version in chrome store

**Comment by aronprins** [comment]
Just sent you an email*

**Comment by autoclick** [comment]
1000$

**Comment by aronprins** [comment]
Can we handle this via email :)
